# Generated by Django 5.2.7 on 2026-01-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(default=2025, verbose_name='Start Year')),
                ('end_year', models.PositiveIntegerField(default=2026, verbose_name='End Year')),
            ],
            options={
                'verbose_name': 'Committee Settings',
                'verbose_name_plural': 'Committee Settings',
            },
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.CharField(choices=[('PRAMUKH', 'Pramukh'), ('UP_PRAMUKH', 'Up-pramukh'), ('MANTRI', 'Mantri'), ('SAH_MANTRI', 'Sah-Mantri'), ('KHAJANCHI', 'Khajanchi'), ('SAMAJIK_CONVENER', 'Samajik Convener'), ('ARTHIC_CONVENER', 'Arthic Convener'), ('SHAIKSHANIK_CONVENER', 'Shaikshanik Convener'), ('KAROBARI_SABHY', 'Karobari Sabhy'), ('AUDITOR', 'Extra Auditor')], max_length=50, verbose_name='Designation'),
        ),
    ]
