# Generated by Django 5.2.7 on 2026-01-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_committeesettings_alter_committeemember_designation'),
        ('people', '0006_remove_person_family_group_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_memberships', to='people.person'),
        ),
    ]
