# Generated by Django 5.2.7 on 2026-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The announcement text to display in the scroller.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility of this announcement.')),
                ('scroll_speed', models.IntegerField(default=20, help_text='Speed in seconds (e.g., 20 = Slow, 10 = Fast).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
