# Generated by Django 6.0 on 2025-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_name_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text')], max_length=10),
        ),
    ]
