# Generated by Django 5.2.7 on 2026-01-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_directory',
            field=models.BooleanField(default=False, verbose_name='Can view People Directory'),
        ),
    ]
