# Generated by Django 5.2.7 on 2026-01-25 06:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_/space only.', max_length=150, unique=True, validators=[accounts.models.SpaceUnicodeUsernameValidator()]),
        ),
    ]
