# Generated by Django 5.2.7 on 2026-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_download_directory',
            field=models.BooleanField(default=False, verbose_name='Can download People Directory'),
        ),
    ]
