# Generated by Django 5.2.7 on 2026-01-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='Suthar', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('native_gam', models.CharField(max_length=100, verbose_name='Native Village (Gam)')),
                ('current_city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'People Directory',
                'ordering': ['first_name'],
            },
        ),
    ]
