# Generated by Django 5.2.7 on 2026-01-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Family Name/Identity')),
                ('village', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-is_family_head', 'first_name'], 'verbose_name_plural': 'People Directory'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_family_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='people.familygroup'),
        ),
    ]
