# Generated by Django 5.2.7 on 2026-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_familygroup_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-is_family_head', 'full_name'], 'verbose_name_plural': 'People Directory'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Full Name'),
        ),
    ]
