# Generated by Django 5.2.7 on 2026-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_first_name_to_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
