# Generated by Django 5.2.7 on 2026-01-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_fullname_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='family_group',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family__hometown', 'full_name'], 'verbose_name_plural': 'People Directory'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_family_head',
        ),
        migrations.RemoveField(
            model_name='person',
            name='native_gam',
        ),
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('DIPLOMA', 'Diploma'), ('GRADUATE', 'Graduate'), ('POST_GRADUATE', 'Post Graduate'), ('DOCTORATE', 'Doctorate'), ('CA', 'CA'), ('CS', 'CS'), ('LLB', 'LLB'), ('MBBS', 'MBBS'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='education_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Education'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Is Head of Family'),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=200, verbose_name='Job/Profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried')], default='UNMARRIED', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='maternal_home',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Maternal Home'),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='parent_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_people', to='people.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='relation_with_head',
            field=models.CharField(choices=[('HEAD', 'Head of Family'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('GRANDSON', 'Grandson'), ('GRANDDAUGHTER', 'Granddaughter'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometown', models.CharField(max_length=100, verbose_name='Home Town')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_family', to='people.person')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['hometown'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.family'),
        ),
        migrations.DeleteModel(
            name='FamilyGroup',
        ),
    ]
